import {
  CarIcon,
  ShopIcon,
  ListIcon,
  DrinkIcon,
  ChartIcon,
  WalletIcon,
  AccountIcon,
  DashboardIcon,
  AmbulanceIcon,
  AlarmIcon,
  BadgeIcon,
  BackpackIcon,
  BallonIcon,
  BandAidIcon,
  BankIcon,
  BaberIcon,
  BedIcon,
  BicycleIcon,
  BookIcon,
  BowlingIcon,
  BoxIcon,
  BoxAltIcon,
  BreadIcon,
  BriefCaseIcon,
  BuildingIcon,
  BulbIcon,
  CakeIcon,
  CameraIcon,
  ChartTreeIcon,
  CheeseIcon,
  ChildIcon,
  CocktailIcon,
  CoffeeIcon,
  CupcakeIcon,
  DrinkAltIcon,
  DrumstickIcon,
  ElearningIcon,
  FlowerBouquetIcon,
  FilmIcon,
  FreshFryIcon,
  GasIcon,
  GiftIcon,
  GamepadIcon,
  GlassCheerIcon,
  GlobeIcon,
  GraduationIcon,
  HamburgerIcon,
  HandHoldingIcon,
  IceCreamIcon,
  IceSkateIcon,
  IdBadgeIcon,
  KeyboardIcon,
  LipStickIcon,
  MakeupBrushIcon,
  MedicineIcon,
  MiscrophoneAltIcon,
  MugIcon,
  MugTeaIcon,
  MapMarkerIcon,
  MoneyIcon,
  PharmancyIcon,
  PlaneIcon,
  PinponIcon,
  PizzaIcon,
  PockerClipIcon,
  PrintIcon,
  ReceiptIcon,
  SaladIcon,
  SandwichIcon,
  SauceIcon,
  SchoolIcon,
  SchoolBusIcon,
  ShopMallIcon,
  ShoppingCartIcon,
  ShoppingBagIcon,
  SoapIcon,
  SpeakerIcon,
  StethoscopeIcon,
  SushiIcon,
  SyringeIcon,
  TacoIcon,
  TaxiIcon,
  TerraceIcon,
  TubeIcon,
  TicketIcon,
  ToothIcon,
  TrainIcon,
  TreatmentIcon,
  TreeIcon,
  TrophyIcon,
  TruckIcon,
  TurkeyIcon,
  UsbIcon,
  VideoCameraIcon,
  WheelChairIcon,
  CardIcon,
  CardsIcon,
  WalletTickIcon,
  WalletAddIcon,
  MoneyTimeIcon,
  MoneysIcon,
  WalletOneIcon,
  walletTwoIcon,
  WalletThreeIcon,
  TicketStartIcon,
  TicketOneIcon,
  SalaryIcon,
  RentalIcon,
  LotteryIcon,
  ChartArrow,
} from "../assets/icons";

export const sideNavOptions = [
  {
    path: "/",
    title: "dashboard",
    icon: <DashboardIcon />,
    activeIcon: <DashboardIcon active />,
  },
  {
    path: "/wallets",
    title: "wallets",
    icon: <WalletIcon />,
    activeIcon: <WalletIcon active />,
  },
  {
    path: "/statistic",
    title: "statistic",
    icon: <ChartIcon />,
    activeIcon: <ChartIcon active />,
  },
  {
    path: "/account",
    title: "account",
    icon: <AccountIcon />,
    activeIcon: <AccountIcon active />,
  },
];

export const bottomNavOptions = [
  {
    path: "/",
    title: "dashboard",
    icon: <DashboardIcon />,
    activeIcon: <DashboardIcon active />,
  },
  {
    path: "/transactions",
    title: "transactions",
    icon: <ListIcon />,
    activeIcon: <ListIcon active />,
  },
  {
    path: "/statistic",
    title: "statistic",
    icon: <ChartIcon />,
    activeIcon: <ChartIcon active />,
  },
  {
    title: "account",
    icon: <AccountIcon />,
    path: "/mobile-account",
    activeIcon: <AccountIcon active />,
  },
];

export const categoryIcons = [
  { name: "ambulance", icon: AmbulanceIcon },
  { name: "alarm", icon: AlarmIcon },
  { name: "badge", icon: BadgeIcon },
  { name: "backpack", icon: BackpackIcon },
  { name: "ballon", icon: BallonIcon },
  { name: "bandaid", icon: BandAidIcon },
  { name: "bank", icon: BankIcon },
  { name: "baber", icon: BaberIcon },
  { name: "bed", icon: BedIcon },
  { name: "bicycle", icon: BicycleIcon },
  { name: "book", icon: BookIcon },
  {
    name: "bowling",
    icon: BowlingIcon,
  },
  { name: "box", icon: BoxIcon },
  { name: "box-alt", icon: BoxAltIcon },
  { name: "bread", icon: BreadIcon },
  { name: "brief-case", icon: BriefCaseIcon },
  { name: "building", icon: BuildingIcon },
  { name: "bulb", icon: BulbIcon },
  { name: "bell-ring", icon: SalaryIcon },
  { name: "cake", icon: CakeIcon },
  { name: "camera", icon: CameraIcon },
  { name: "car", icon: CarIcon },
  { name: "chart-arrow-grow", icon: ChartArrow },
  { name: "chart-tree", icon: ChartTreeIcon },
  { name: "cheese", icon: CheeseIcon },
  { name: "child", icon: ChildIcon },
  { name: "cocktail", icon: CocktailIcon },
  { name: "coffee", icon: CoffeeIcon },
  { name: "cup-cake", icon: CupcakeIcon },
  { name: "drink", icon: DrinkIcon },
  { name: "drink-alt", icon: DrinkAltIcon },
  { name: "drumstick", icon: DrumstickIcon },
  { name: "e-learning", icon: ElearningIcon },
  { name: "flower-bouquet", icon: FlowerBouquetIcon },
  { name: "film", icon: FilmIcon },
  { name: "fresh-fry", icon: FreshFryIcon },
  { name: "gas", icon: GasIcon },
  { name: "gift", icon: GiftIcon },
  { name: "game-pad", icon: GamepadIcon },
  { name: "glass-cheer", icon: GlassCheerIcon },
  { name: "globe", icon: GlobeIcon },
  { name: "graduation", icon: GraduationIcon },
  { name: "home", icon: RentalIcon },
  { name: "hamburger", icon: HamburgerIcon },
  { name: "hand-holding", icon: HandHoldingIcon },
  { name: "ice-cream", icon: IceCreamIcon },
  { name: "ice-skate", icon: IceSkateIcon },
  { name: "id-badge", icon: IdBadgeIcon },
  { name: "keyboard", icon: KeyboardIcon },
  { name: "lipstick", icon: LipStickIcon },
  { name: "makeup-brush", icon: MakeupBrushIcon },
  { name: "medicine", icon: MedicineIcon },
  { name: "miscrophone", icon: MiscrophoneAltIcon },
  { name: "mug", icon: MugIcon },
  { name: "mug-tea", icon: MugTeaIcon },
  { name: "map-marker", icon: MapMarkerIcon },
  { name: "money", icon: MoneyIcon },
  { name: "pharmancy", icon: PharmancyIcon },
  { name: "plane", icon: PlaneIcon },
  { name: "pinpon", icon: PinponIcon },
  { name: "pizza", icon: PizzaIcon },
  { name: "pocker-clip", icon: PockerClipIcon },
  { name: "playing-cards", icon: LotteryIcon },
  { name: "print", icon: PrintIcon },
  { name: "receipt", icon: ReceiptIcon },
  { name: "salad", icon: SaladIcon },
  { name: "sandwich", icon: SandwichIcon },
  { name: "sauce", icon: SauceIcon },
  { name: "school", icon: SchoolIcon },
  { name: "school-bus", icon: SchoolBusIcon },
  { name: "ship", icon: SchoolBusIcon },
  { name: "shop-mall", icon: ShopMallIcon },
  { name: "shopping-cart", icon: ShoppingCartIcon },
  { name: "shopping-bag", icon: ShoppingBagIcon },
  { name: "soap", icon: SoapIcon },
  { name: "speaker", icon: SpeakerIcon },
  { name: "stetho-scope", icon: StethoscopeIcon },
  { name: "sushi", icon: SushiIcon },
  { name: "syringe", icon: SyringeIcon },
  { name: "taco", icon: TacoIcon },
  { name: "taxi", icon: TaxiIcon },
  { name: "terrace", icon: TerraceIcon },
  {
    name: "tube",
    icon: TubeIcon,
  },
  { name: "ticket", icon: TicketIcon },
  { name: "tooth", icon: ToothIcon },
  { name: "train", icon: TrainIcon },
  { name: "treatment", icon: TreatmentIcon },
  { name: "tree", icon: TreeIcon },
  { name: "trophy", icon: TrophyIcon },
  { name: "truck", icon: TruckIcon },
  { name: "turkey", icon: TurkeyIcon },
  {
    name: "usb",
    icon: UsbIcon,
  },
  { name: "video", icon: VideoCameraIcon },
  { name: "wheel", icon: WheelChairIcon },

  { name: "shopping", icon: ShopIcon },
  { name: "drinking", icon: DrinkIcon },
  { name: "hangout", icon: CarIcon },
];

export const walletIcons = [
  {
    _id: "d5ff6bf9-502c-4a09-8705-2ce3abb72c4b",
    name: "card",
    icon: CardIcon,
  },
  {
    _id: "e74ad015-1c2b-49a8-a4ae-6e40d4f1f648",
    name: "cards",
    icon: CardsIcon,
  },
  {
    _id: "5987d34c-467d-4a74-a138-809035dde557",
    name: "wallet-tick",
    icon: WalletTickIcon,
  },
  {
    _id: "77528a02-72ac-4146-8498-17ca89fbc603",
    name: "wallet-add",
    icon: WalletAddIcon,
  },
  {
    _id: "8444dd92-469f-4c8c-8107-57237217ba1d",
    name: "money-time",
    icon: MoneyTimeIcon,
  },
  {
    _id: "9b46020d-d1aa-4e0f-812b-94e67b7f3c5e",
    name: "moneys",
    icon: MoneysIcon,
  },
  {
    _id: "85491424-6e91-46f4-b418-b583bfc41919",
    name: "wallet-one",
    icon: WalletOneIcon,
  },
  {
    _id: "7f330109-ae1f-47e6-82e3-af073f6926c1",
    name: "wallet-two",
    icon: walletTwoIcon,
  },
  {
    _id: "29c1ce35-54d4-48dd-9040-e1b361501538",
    name: "wallet-three",
    icon: WalletThreeIcon,
  },
  {
    _id: "10de7c6c-51de-4eee-ad2d-fc04a516305b",
    name: "ticket-start",
    icon: TicketStartIcon,
  },
  { _id: "0bb9be1a-def8-4c02-b51c-a44a74bffdcb", name: "ticket", icon: TicketIcon },
  { _id: "96b8a7ef-d162-4f28-a189-f933327d2c2c", name: "ticket-one", icon: TicketOneIcon },
];

export const COLOR_OPTIONS = [
  "#ef4444",
  "#f97316",
  "#f59e0b",
  "#eab308",
  "#84cc16",
  "#22c55e",
  "#10b981",
  "#14b8a6",
  "#06b6d4",
  "#0ea5e9",
  "#3b82f6",
  "#6366f1",
  "#8b5cf6",
  "#a855f7",
  // "#d946ef",
];
