export const GET_TRANS_REQUEST = "GET_TRANS_REQUEST";
export const GET_TRANS_FAIL = "GET_TRANS_FAIL";
export const GET_TRANS_SUCCESS = "GET_TRANS_SUCCESS";

export const GET_TRAN_REQUEST = "GET_TRAN_REQUEST";
export const GET_TRAN_FAIL = "GET_TRAN_FAIL";
export const GET_TRAN_SUCCESS = "GET_TRAN_SUCCESS";

export const ADD_TRAN_REQUEST = "ADD_TRAN_REQUEST";
export const ADD_TRAN_FAIL = "ADD_TRAN_FAIL";
export const ADD_TRAN_SUCCESS = "ADD_TRAN_SUCCESS";

export const DELETE_TRAN_REQUEST = "DELETE_TRAN_REQUEST";
export const DELETE_TRAN_FAIL = "DELETE_TRAN_FAIL";
export const DELETE_TRAN_SUCCESS = "DELETE_TRAN_SUCCESS";

export const UPDATE_TRAN_REQUEST = "UPDATE_TRAN_REQUEST";
export const UPDATE_TRAN_FAIL = "UPDATE_TRAN_FAIL";
export const UPDATE_TRAN_SUCCESS = "UPDATE_TRAN_SUCCESS";

export const MONTHLY_STATS_REQUEST = "MONTHLY_STATS_REQUEST";
export const MONTHLY_STATS_FAIL = "MONTHLY_STATS_FAIL";
export const MONTHLY_STATS_SUCCESS = "MONTHLY_STATS_SUCCESS";

export const ANNUAL_STATS_REQUEST = "ANNUAL_STATS_REQUEST";
export const ANNUAL_STATS_FAIL = "ANNUAL_STATS_FAIL";
export const ANNUAL_STATS_SUCCESS = "ANNUAL_STATS_SUCCESS";

export const RESET_ERROR = "RESET_ERROR";
export const RESET_SUCCESS = "RESET_SUCCESS";
