// action types for authentication
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_FAIL = "OTP_FAIL";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const RESET_OTP_ERROR = "RESET_OTP_ERROR";
export const RESET_OTP_SUCCESS = "RESET_OTP_SUCCESS";

export const SET_EXPIRED = "SET_EXPIRED";
export const SET_LOGOUT = "SET_LOGOUT";

// action types to get and update user information
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const RESET_PROFILE_ERROR = "RESET_PROFILE_ERROR";
export const RESET_PROFILE_SUCCESS = "RESET_PROFILE_SUCCESS";

export const UPDATE_PASS_REQUEST = "UPDATE_PASS_REQUEST";
export const UPDATE_PASS_FAIL = "UPDATE_PASS_FAIL";
export const UPDATE_PASS_SUCCESS = "UPDATE_PASS_SUCCESS";

export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
