export const GET_WALLETS_REQUEST = "GET_WALLETS_REQUEST";
export const GET_WALLETS_FAIL = "GET_WALLETS_FAIL";
export const GET_WALLETS_SUCCESS = "GET_WALLETS_SUCCESS";

export const GET_WALLET_REQUEST = "GET_WALLET_REQUEST";
export const GET_WALLET_FAIL = "GET_WALLET_FAIL";
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";
export const RESET_GET_ERROR = "RESET_GET_ERROR";

export const ADD_WALLET_REQUEST = "ADD_WALLET_REQUEST";
export const ADD_WALLET_FAIL = "ADD_WALLET_FAIL";
export const ADD_WALLET_SUCCESS = "ADD_WALLET_SUCCESS";

export const DELETE_WALLET_REQUEST = "DELETE_WALLET_REQUEST";
export const DELETE_WALLET_FAIL = "DELETE_WALLET_FAIL";
export const DELETE_WALLET_SUCCESS = "DELETE_WALLET_SUCCESS";

export const UPDATE_WALLET_REQUEST = "UPDATE_WALLET_REQUEST";
export const UPDATE_WALLET_FAIL = "UPDATE_WALLET_FAIL";
export const UPDATE_WALLET_SUCCESS = "UPDATE_WALLET_SUCCESS";

export const GET_STATS_REQUEST = "GET_WALLET_STATS";
export const GET_STATS_FAIL = "GET_STATS_FAIL";
export const GET_STATS_SUCCESS = "GET_STATS_SUCCESS";
export const RESET_STATS = "RESET_STATS";

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";
